name: 'Songmu/tagpr'
description: I don't want to manage the dependency in multiple repositories.

inputs:
  github-token:
    description: 'GitHub token'
    required: true

outputs:
  tag:
    description: "The semver tag, which is output only when the tagpr has tagged"
    value: ${{ steps.tagpr.outputs.tag }}
  pull_request:
    description: "Information of the pull request created by tagpr in JSON format"
    value: ${{ steps.tagpr.outputs.pull_request }}

runs:
  using: composite
  steps:
    - uses: Songmu/tagpr@7191605433b03e11b313dbbc0efb80185170de4b # v1.9.0
      id: tagpr
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
