name: 'Songmu/tagpr'
description: I don't want to manage the dependency in multiple repositories.

inputs:
  app-id:
    description: 'The GitHub App ID'
    required: true
  private-key:
    description: 'The private key of the GitHub App'
    required: true

outputs:
  tag:
    description: "The semver tag, which is output only when the tagpr has tagged"
    value: ${{ steps.tagpr.outputs.tag }}
  pull_request:
    description: "Information of the pull request created by tagpr in JSON format"
    value: ${{ steps.tagpr.outputs.pull_request }}

runs:
  using: composite
  steps:
    - uses: actions/create-github-app-token@v1
      id: token
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}

    - uses: Songmu/tagpr@d73c022fee724bfaeed260ef5f509724c45dc980 # v1.1.2
      id: tagpr
      env:
        GITHUB_TOKEN: ${{ steps.token.outputs.token }}
